# ML Zoomcamp Course Homework

## 01 - Introduction

In [1]:
import numpy as np
import pandas as pd

### Question 1
#### What's the version of NumPy that you installed?

In [2]:

np.__version__


'1.21.1'

### Question 2
#### What's the version of Pandas?

In [3]:
pd.__version__

'1.3.1'

<div class="alert alert-info">
  <strong>The following questions use the price car dataset. You should place it under 'data/car_price.csv' .</strong>
</div>

In [4]:
cars_df = pd.read_csv('data/car_price.csv')
cars_df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

### Question 3
#### What's the average price of BMW cars in the dataset?

In [5]:
cars_df.loc[cars_df['Make'] == 'BMW','MSRP'].mean()

61546.76347305389

### Question 4
#### Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [6]:
cars_df.loc[cars_df['Year'] >= 2015,'Engine HP'].isna().sum()

51

### Question 5
#### Calculate the average "Engine HP" in the dataset.

In [7]:
engine_hps = cars_df.loc[cars_df['Year'] >= 2015,'Engine HP']
mean_hp_before = engine_hps.mean()
print(f'Average Engine HPs after 2015: {mean_hp_before}')

Average Engine HPs after 2015: 272.98771870794076


#### Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
#### Now, calcualte the average of "Engine HP" again.

In [8]:
mean_hp_after = engine_hps.fillna(mean_hp_before).mean()
print(f'Average Engine HPs before filling NAs: {round(mean_hp_before)}')
print(f'Average Engine HPs after filling NAs: {round(mean_hp_after)}')


Average Engine HPs before filling NAs: 273
Average Engine HPs after filling NAs: 273


### Question 6
#### Select all the "Rolls-Royce" cars from the dataset.
#### Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
#### Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).

In [9]:
rolls_royces = cars_df.loc[cars_df['Make'] == 'Rolls-Royce',['Engine HP', 'Engine Cylinders', 'highway MPG']].drop_duplicates()
rolls_royces

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

#### Get the underlying NumPy array. Let's call it X.
#### Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
#### Invert XTX.
#### What's the sum of all the elements of the result?

In [10]:
X = rolls_royces.values
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [11]:
XTX = np.matmul(X.T,X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [12]:
iXTX = np.linalg.inv(XTX)
iXTX.sum()

0.032212320677486125

### Question 7

#### Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].


In [13]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

#### Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
#### What's the value of the first element of w?.

In [14]:
w = np.matmul(np.matmul(iXTX,X.T),y)
w[0]

0.19989598183188972