# ML Zoomcamp Course Homework

## 01 - Introduction

In [1]:
import numpy as np
import pandas as pd

### Question 1
#### What's the version of NumPy that you installed?

In [2]:

np.__version__


'1.21.5'

<div class="alert alert-info">
  <strong>The following questions use the price car dataset. You should place it under 'data/car_price.csv' .</strong>
</div>

### Question 2
How many records are in the dataset?

In [3]:
cars_df = pd.read_csv('data/car-price.csv')
len(cars_df)

11914

In [4]:
cars_df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

### Question 3
#### Who are the most frequent car manufacturers (top-3) according to the dataset?

In [5]:
cars_df['Make'].value_counts().head(3)

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

### Question 4
#### What's the number of unique Audi car models in the dataset?

In [6]:
len(cars_df.loc[cars_df['Make'] == 'Audi', 'Model'].unique())

34

In [7]:
### Question 5
#### How many columns in the dataset have missing values?

In [8]:
cars_df.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [9]:
sum(cars_df.isna().sum() > 0)

5

### Question 6
Find the median value of "Engine Cylinders" column in the dataset.

Next, calculate the most frequent value of the same "Engine Cylinders".

Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent 
value from the previous step.

Now, calculate the median value of "Engine Cylinders" once again.

Has it changed?

In [10]:
cylinders = cars_df['Engine Cylinders']
cylinders.median()

6.0

In [11]:
cylinders_filledna = cylinders.fillna(cylinders.mode().head(1)[0])
cylinders_filledna.median()

6.0

In [12]:
cylinders.median() != cylinders_filledna.median()

False

### Question 7


Select all the "Lotus" cars from the dataset.

Select only columns "Engine HP", "Engine Cylinders".

Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).

Get the underlying NumPy array. Let's call it X.

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

Compute the inverse of XTX.

Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

What's the value of the first element of w?

In [13]:
all_lotus = cars_df.loc[cars_df['Make'] == 'Lotus', ['Engine HP', 'Engine Cylinders']].drop_duplicates()
all_lotus

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [14]:
X = all_lotus.values
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [15]:
XTX = np.matmul(X.T,X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [16]:
iXTX = np.linalg.inv(XTX)
iXTX

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [17]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
w = np.matmul(np.matmul(iXTX,X.T),y)
w[0]

4.594944810094551